### PR TITLE
fix: Use non-panicking AddressFromBytes and NewCoinSafe

### LINKED ISSUE #219: AddressToBech32(), AddressFromBytes() and NewCoin() can panic
`crypto.AddressToBech32()`, `crypto.AddressFromBytes()` and `std.NewCoin()` can panic. The API code calls these in several places. We should recover and return an error.

### PR DESCRIPTION
**Pull request by jefft0**
This is a follow-on to PR https://github.com/gnolang/gnonative/pull/220 and finishes to resolve issue #219.

* Update to the latest gnolang/gno which includes PR https://github.com/gnolang/gno/pull/5329
* In api.go, use the non-panicking updated `AddressFromBytes` and use the new non-panicking `NewCoinSafe`

### CODE REVIEW

File: service/api.go [hunk 1]
```diff
@@ -642,24 +678,41 @@ func (s *gnoNativeService) convertRunRequest(req *api_gen.RunRequest) (*gnoclien
 				},
 			},
 		}
+		addr, err := crypto.AddressFromBytes(req.CallerAddress)
+		if err != nil {
+			return nil, nil, getGrpcError(err)
+		}
```
Comment (D4ryl00) [inline service/api.go]: Move AddressFromBytes(req.CallerAddress) outside the loop.

File: service/api.go [hunk 2]
```diff
@@ -580,10 +604,22 @@ func (s *gnoNativeService) convertSendRequest(req *api_gen.SendRequest) (*gnocli
 	msgs := make([]bank.MsgSend, 0)
 
 	for _, msg := range req.Msgs {
+		fromAddr, err := crypto.AddressFromBytes(req.CallerAddress)
+		if err != nil {
+			return nil, nil, getGrpcError(err)
+		}
```
Comment (D4ryl00) [inline service/api.go]: Move AddressFromBytes(req.CallerAddress) outside the loop.

File: service/api.go [hunk 3]
```diff
@@ -517,13 +529,25 @@ func (s *gnoNativeService) convertCallRequest(req *api_gen.CallRequest) (*gnocli
 	msgs := make([]vm.MsgCall, 0)
 
 	for _, msg := range req.Msgs {
+		addr, err := crypto.AddressFromBytes(req.CallerAddress)
+		if err != nil {
+			return nil, nil, getGrpcError(err)
+		}
```
Comment (D4ryl00) [inline service/api.go]: Move AddressFromBytes(req.CallerAddress) outside the loop.

**Review by D4ryl00 — APPROVED** [review]
Please see my comments, otherwise LGTM.

File: service/api.go (hunk 1 above)
Comment (jefft0) [reply service/api.go]: Done. https://github.com/gnolang/gnonative/pull/221/changes/5ea88980f761c21c4bdecf7ae0c268ec18dba73e

File: service/api.go (hunk 2 above)
Comment (jefft0) [reply service/api.go]: Done. https://github.com/gnolang/gnonative/pull/221/changes/5ea88980f761c21c4bdecf7ae0c268ec18dba73e

File: service/api.go (hunk 3 above)
Comment (jefft0) [reply service/api.go]: Done. https://github.com/gnolang/gnonative/pull/221/changes/5ea88980f761c21c4bdecf7ae0c268ec18dba73e
